name: Update README

on:
  schedule:
    # Cada 12 horas
    - cron: "0 */12 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update GitHub activity in README
        uses: jamesgeorge007/github-activity-readme@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
