name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"  # cada 12 horas
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout del repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Usa la acción oficial
      - name: Update GitHub activity in README
        uses: jamesgeorge007/github-activity-readme@v0.1.0

        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

