name: Update README4

on:
  schedule:
    - cron: "0 */12 * * *"  # cada 12 horas
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout de tu repositorio
      - name: Checkout repo
        uses: actions/checkout@v3

      # Usar la acción oficial (no tu usuario)
      - name: Update GitHub activity in README
        uses: jamesgeorge007/github-activity-readme@v0.2.1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

