name: Update README2

on:
  schedule:
    - cron: '* */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/marcela-svg
      - uses: jamesgeorge007/github-activity-marcela-svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
